# Generated by Django 5.2.9 on 2026-01-01 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("problems", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("python", "Python"),
                            ("java", "Java"),
                            ("cpp", "C++"),
                            ("c", "C"),
                            ("javascript", "JavaScript"),
                            ("kotlin", "Kotlin"),
                            ("scala", "Scala"),
                            ("csharp", "C#"),
                            ("fsharp", "F#"),
                            ("rust", "Rust"),
                            ("go", "Go"),
                            ("php", "PHP"),
                            ("ruby", "Ruby"),
                            ("perl", "Perl"),
                            ("lua", "Lua"),
                            ("haskell", "Haskell"),
                            ("clojure", "Clojure"),
                            ("erlang", "Erlang"),
                            ("elixir", "Elixir"),
                            ("r", "R"),
                            ("julia", "Julia"),
                            ("swift", "Swift"),
                            ("dart", "Dart"),
                            ("objectivec", "Objective-C"),
                        ],
                        max_length=20,
                    ),
                ),
                ("code", models.TextField()),
                ("result", models.CharField(default="pending", max_length=20)),
                ("execution_time", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="problems.problem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
