# Generated by Django 5.2.9 on 2026-01-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0002_alter_submission_result"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgrammingLanguage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=30, unique=True)),
                ("display_name", models.CharField(max_length=50)),
                ("file_extension", models.CharField(max_length=10)),
                ("docker_image", models.CharField(max_length=100)),
                ("compile_command", models.TextField(blank=True, null=True)),
                ("run_command", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Submission",
        ),
    ]
